version: '3.9'

services:
    merchandise_service:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - supply-service
            - emailing-service
            - employees-service            
            - stock-api
    supply-service:
        image: "ghcr.io/ozontech-route256-cource-project/supply-service:main"
        ports:
            - "8001:80"
    emailing-service:
        image: "ghcr.io/ozontech-route256-cource-project/emailing-service:main"
        ports:
            - "8002:80"
    employees-service:
        image: "ghcr.io/ozontech-route256-cource-project/employees-service:main"
        ports:
            - "8003:80"
    stock-api:
        image: "ghcr.io/ozontech-route256-cource-project/stock-api:main"
        ports:
            - "8004:80"